name: deploy functions in parallel

on:
  pull_request:
    branches: [master]

env:
  BRANCH: ${{ github.event.pull_request.head.ref }}
  BODY: ${{ github.event.pull_request.body }}
  
jobs:
  get_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install script dependencies
        working-directory: ./.github/scripts
        run: npm install  

      - name: Run script
        shell: bash
        working-directory: ./.github/scripts
        run: |
          FUNCTIONS=$(node getFunctions.js ${BRANCH} ${BODY})
          echo "FUNCTIONS=$FUNCTIONS" >> $GITHUB_ENV

      - name: Check folder
        shell: bash
        working-directory: ./.github/scripts
        run: |
          echo ${{ env.FUNCTIONS }} > functions-${BRANCH}.json
          cat functions-${BRANCH}.json