name: Deploy to Homolog

on:
  workflow_dispatch:
  push:
    branches:
      - homolog

env:
  PROJECT: ${{ secrets.PROJECT_ID_TEST }}
  HMG_FUNCTIONS_FILE: hmg-functions
  FUNCTIONS_PATH: deploy-functions
  EMPTY_FILE: empty-functions

jobs:
  get_functions:
    runs-on: ubuntu-latest
    outputs:
      functions: ${{ steps.get-functions.outputs.functions }}
    steps:
      - uses: actions/checkout@v3

      - name: Install script dependencies
        working-directory: ./.github/scripts
        run: npm install

      - name: Create deploy functions file
        working-directory: ./.github/scripts
        run: |
          mkdir ${{ env.FUNCTIONS_PATH }}
          echo [] > ./${{ env.FUNCTIONS_PATH }}/${{ env.FUNCTIONS_PATH }}.json

      - name: Download homolog functions artifact
        working-directory: ./.github/scripts
        env:
          ARTIFACT_NAME: ${{ env.HMG_FUNCTIONS_FILE }}
          REPOSITORY: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FUNCTIONS_PATH: ${{ env.HMG_FUNCTIONS_FILE }}
          ARTIFACT_TYPE: byName
        run: node getArtifacts.js

      - name: Define deploy functions
        working-directory: ./.github/scripts
        env:
          BRANCH_FUNCTIONS_FILE: ./${{ env.FUNCTIONS_PATH }}/${{ env.FUNCTIONS_PATH }}.json
          HOMOLOG_FUNCTIONS_FILE: ./${{ env.HMG_FUNCTIONS_FILE }}/${{ env.HMG_FUNCTIONS_FILE }}.json
          OPERATION_TYPE: retrieve
        run: node defineHmgFunctions.js

      - name: Delete current homolog functions artifact
        working-directory: ./.github/scripts
        env:
          ARTIFACT_NAME: ${{ env.HMG_FUNCTIONS_FILE }}
          REPOSITORY: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_TYPE: byName
        run: node deleteArtifact.js
      
      - name: Upload new homolog functions artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.HMG_FUNCTIONS_FILE }}
          path: ./.github/scripts/${{ env.HMG_FUNCTIONS_FILE }}/${{ env.HMG_FUNCTIONS_FILE }}.json

      - name: Check if there are functions to be deployed
        id: check-functions
        shell: bash
        working-directory: ./.github/scripts
        continue-on-error: true
        env:
          FUNCTIONS_FILE: ./${{ env.FUNCTIONS_PATH }}/${{ env.FUNCTIONS_PATH }}.json
        run: |
          node checkIfThereAreFunctions.js
          exit_code=$?
          echo "::set-output name=deploy-ready::$exit_code"
      
      - name: Create special functions file to not run deploy if there are no functions to be deployed
        working-directory: ./.github/scripts
        run: |
          echo ['"${{ env.EMPTY_FILE }}"'] > ./${{ env.FUNCTIONS_PATH }}/${{ env.EMPTY_FILE }}.json

      
      - name: Add functions array to output
        id: get-functions
        run: |
          if [ ${{ steps.check-functions.outputs.deploy-ready }} -eq 0 ]; then FUNCTIONS=$(echo $(cat .github/scripts/${{ env.FUNCTIONS_PATH }}/${{ env.FUNCTIONS_PATH }}.json) | sed 's/ //g' ); else FUNCTIONS=$(echo $(cat .github/scripts/${{ env.FUNCTIONS_PATH }}/${{ env.EMPTY_FILE }}.json) | sed 's/ //g' ); fi
          echo "::set-output name=functions::$FUNCTIONS"

  deploy:
    runs-on: ubuntu-latest
    needs: [get_functions]
    strategy:
      matrix:
        function: ${{ fromJson(needs.get_functions.outputs.functions) }}
    steps:
      - name: Print
        if: fromJson(needs.get_functions.outputs.functions)[0] != 'empty-functions'
        run: echo ${{ matrix.function }}


