name: Deploy to Prod

on:
  workflow_dispatch:

env:
  PROJECT: ${{ secrets.PROJECT_ID_TEST }}
  PROD_FUNCTIONS_FILE: prod-functions
  EMPTY_FILE: empty-functions

jobs:
  get_functions:
    runs-on: ubuntu-latest
    outputs:
      functions: ${{ steps.get-functions.outputs.functions }}
    steps:
      - uses: actions/checkout@v3

      - name: Install script dependencies
        working-directory: ./.github/scripts
        run: npm install

      - name: Create deploy functions file
        working-directory: ./.github/scripts
        run: mkdir ${{ env.PROD_FUNCTIONS_FILE }}

      - name: Download prod functions artifact
        working-directory: ./.github/scripts
        env:
          ARTIFACT_NAME: ${{ env.PROD_FUNCTIONS_FILE }}
          REPOSITORY: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FUNCTIONS_PATH: ${{ env.PROD_FUNCTIONS_FILE }}
          ARTIFACT_TYPE: byName
        run: node getArtifacts.js

      - name: Check if there are functions to be deployed
        id: check-functions
        shell: bash
        working-directory: ./.github/scripts
        continue-on-error: true
        env:
          FUNCTIONS_FILE: ./${{ env.PROD_FUNCTIONS_FILE }}/${{ env.PROD_FUNCTIONS_FILE }}.json
        run: |
          node checkIfThereAreFunctions.js
          exit_code=$?
          echo "::set-output name=deploy-ready::$exit_code"

      - name: Create special functions file to not run deploy if there are no functions to be deployed
        working-directory: ./.github/scripts
        run: |
          echo ['"${{ env.EMPTY_FILE }}"'] > ./${{ env.PROD_FUNCTIONS_FILE }}/${{ env.EMPTY_FILE }}.json

      - name: Add functions array to output
        id: get-functions
        run: |
          if [ ${{ steps.check-functions.outputs.deploy-ready }} -eq 0 ]; then FUNCTIONS=$(echo $(cat .github/scripts/${{ env.PROD_FUNCTIONS_FILE }}/${{ env.PROD_FUNCTIONS_FILE }}.json) | sed 's/ //g' ); else FUNCTIONS=$(echo $(cat .github/scripts/${{ env.PROD_FUNCTIONS_FILE }}/${{ env.EMPTY_FILE }}.json) | sed 's/ //g' ); fi
          echo "::set-output name=functions::$FUNCTIONS"

  deploy:
    runs-on: ubuntu-latest
    needs: [get_functions]
    strategy:
      matrix:
        function: ${{ fromJson(needs.get_functions.outputs.functions) }}
    steps:
      - name: Deploy
        if: fromJson(needs.get_functions.outputs.functions)[0] != 'empty-functions'
        run: echo ${{ matrix.function }}

  delete_prod_functions_artifact:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v3

      - name: Install script dependencies
        working-directory: ./.github/scripts
        run: npm install

      - name: Delete branch functions artifact
        working-directory: ./.github/scripts
        env:
          ARTIFACT_NAME: ${{ env.PROD_FUNCTIONS_FILE }}
          REPOSITORY: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_TYPE: byName
        run: node deleteArtifact.js