name: Deploy to Prod

# on:
#   workflow_dispatch:

on:
  pull_request:
    branches: [develop]

env:
  PROJECT: ${{ secrets.PROJECT_ID_TEST }}
  PROD_FUNCTIONS_FILE: prod-functions
  FUNCTIONS_PATH: deploy-functions

jobs:
  get_functions:
    runs-on: ubuntu-latest
    outputs:
      functions: ${{ steps.get-functions.outputs.functions }}
    steps:
      - uses: actions/checkout@v3

      - name: stop process
        run: exit 0

      - name: Job should not run
        run: echo "Should not run"

      # - name: Install script dependencies
      #   working-directory: ./.github/scripts
      #   run: npm install

      # - name: Create deploy functions file
      #   working-directory: ./.github/scripts
      #   run: |
      #     mkdir ${{ env.FUNCTIONS_PATH }}
      #     echo [] > ./${{ env.FUNCTIONS_PATH }}/${{ env.FUNCTIONS_PATH }}.json

      # - name: Add functions array to output
      #   id: get-functions
      #   run: |
      #     FUNCTIONS=$(echo $(cat .github/scripts/${{ env.FUNCTIONS_PATH }}/${{ env.FUNCTIONS_PATH }}.json) | sed 's/ //g' )
      #     echo "::set-output name=functions::$FUNCTIONS"
  should_not_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Job should not run
        run: echo "Should not run"