
name: Deploy to test

# on:
#   workflow_dispatch:
#   pull_request:
#     branches:
#       - develop
#     types: [closed]

on:
  pull_request:
    branches: [develop]

env:
  PROJECT: ${{ secrets.PROJECT_ID_TEST }}
  BRANCH: ${{ github.event.pull_request.head.ref }}
  FUNCTIONS_PATH: deploy-functions

jobs:
  get_functions:
    runs-on: ubuntu-latest
    outputs:
      functions: ${{ steps.get-functions.outputs.functions }}
    steps:
      - uses: actions/checkout@v3

      - name: Install script dependencies
        working-directory: ./.github/scripts
        run: npm install

      - name: Create functions folder
        working-directory: ./.github/scripts
        run: mkdir ${{ env.FUNCTIONS_PATH }}

      - name: Download branch functions artifact
        working-directory: ./.github/scripts
        env:
          ARTIFACT_NAME: ${{ env.BRANCH }}
          REPOSITORY: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FUNCTIONS_PATH: ${{ env.FUNCTIONS_PATH }}
          ARTIFACT_TYPE: byBranch
        run: node getArtifacts.js

      - name: Remove branch invalid char
        shell: bash
        run: |
          RENAMED_BRANCH="${BRANCH////$'-'}"
          echo "RENAMED_BRANCH=$RENAMED_BRANCH" >> $GITHUB_ENV

      - name: Add functions array to output
        id: get-functions
        run: |
          FUNCTIONS=$(echo $(cat .github/scripts/${FUNCTIONS_PATH}/functions-${{ env.RENAMED_BRANCH }}.json) | sed 's/ //g' )
          echo "::set-output name=functions::$FUNCTIONS"

  deploy:
    # if: fromJson(needs.get_functions.outputs.functions) != [] 
    runs-on: ubuntu-latest
    needs: [get_functions]
    strategy:
      matrix:
        function: ${{ fromJson(needs.get_functions.outputs.functions) }}
    steps:
      - name: Print
        run: echo ${{ matrix.function }}

  upload_functions_hmg:
    # if: fromJson(needs.get_functions.outputs.functions) != []
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Create branch functions json file
        shell: bash
        working-directory: ./.github/scripts
        run: |
          echo ${{ needs.get_functions.outputs.functions }} > branch-functions.json
          cat branch-functions.json